### ISSUE TITLE
Implement Power-Up System

### ISSUE THREAD

**Issue by dalderliesten** [dalderliesten/Scrumbledore#223]
A power-up system should be created that allows power-ups to be added to the game and to the levels.  The player and enemies should be able to pick these up.

Suggestions for power-ups:

-Extra Speed
-Extra Jump-Height
-Bigger Bubbles

**Comment by jessetilro** [comment]
Power-Up suggestion: fire balls (like original game).

**Comment by jessetilro** [comment]
The eventual Powerups that were agreed upon:
* __BlueBerry Bubble__
 * Shoot larger bubbles.
 * Duration 10 seconds.
 * 225% normal bubble size.
* __Pyro Pepper__
 * Shoot fireballs.
 * Duration 5 seconds.
* __Chili Chicken__
 * Move faster.
 * Duration 5 seconds.
 * 150% normal speed.
* __Turtle Taco__
 * Be shielded, yielding immortality.
 * Duration 5 seconds.

**Comment by FlorisXll** [comment]
To do:

- BlueBubble must encapsulate up to 3 enemies: BlueBubble begins with lifetime 3. The lifetime decreases when it encapsulated an enemy. Warning: only the first time you encapsulate an enemy you must add the BlueBubble to the enemy bubble list otherwise the level will be finished before killing all bubbles with enemies in them.
- Add missing JavaDoc
- Fix collision bug when shooting Fireballs and BlueBubbles.
- Fix collision between Fireballs and other sort of projectiles (Fireball passes through everything, maybe even destroyes all bubbles on colliding?).
- When picking up multiple power-ups you should get all the attributes of these power-ups. Currently you can't get Chili and Turtle at the same time.
- Add correct sprites to all projectiles.
- Finally fine-tune the constants so that using the power-ups feels natural.

While implementing you might get a large complexity. This is hard to avoid and such a high time pressure.
