### ISSUE TITLE
Fix powerup animation rendering

### ISSUE THREAD

**Issue by jmeijer8** [dalderliesten/Scrumbledore#278]
When a player dies while still under the influence of a powerup, the powerup animation does not dissapear. <bug

**Comment by NielsWarnars** [comment]
Problem seems to be caused by the GameDisplay.renderDynamic() method.

Whenever a player dies it is still present in a game, its 'alive'-status is only set to 'false', but within the GameDisplay.renderDynamic() method all dynamic elements are rendered using: 
renderLevelElements(currentGame.getCurrentLevel().getDynamicElements(), dynamicContext);

In this case also a dead player would be rendered if it has a sprite.

Possible solutions:
1. Convert a power-up-having player back to a normal player so it would no be rendered.
2. Only render players who are alive.
